config/routes.rb
Rails.application.routes.draw do
  root 'surveys#home'

  devise_for :users

  resources :answers

  resources :questions

  resources :surveys do
    resources :submissions
  end

  get '/home', to: 'surveys#home'
  get '/mysurveys', to: 'surveys#mysurveys'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question, inverse_of: :answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey, inverse_of: :questions
  has_many :answers, inverse_of: :question
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: proc { |attributes| attributes[:content].blank? }

  def answers_for_form
    collection = answers.where(survey_id: id)
    collection.any? ? collection : answers.build
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :survey
  belongs_to :user
end

app/models/sumbission.rb
class Submission < ActiveRecord::Base
  belongs_to :survey
  belongs_to :user
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :questions, inverse_of: :survey
  has_many :answers

  has_many :submissions
  has_many :users, through: :submissions

  # has_many :answers, though: :questions
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: proc { |attributes| attributes[:prompt].blank? }

  def questions_for_form
    collection = questions.where(survey_id: id)
    collection.any? ? collection : questions.build
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :surveys
  has_many :submissions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def new
  end

  def create
  end

  private

  def submission_params
    params[:submission].permit(:survey_id, :user_id)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, except: [:index, :new, :create, :home, :mysurveys]
  before_action :authenticate_user!, except: [:index, :show]

  def home
  end

  def mysurveys
    @current_user = current_user
    @surveys = Survey.where(user_id: current_user.id)
  end

  def index
    @surveys = Survey.all.reject { |s| s.user_id == current_user.id }
  end

  def show
    @survey.submissions.build
  end

  def new
    @survey = Survey.new
    @survey.questions.build
    # @submission = Submission.new
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.user = current_user
    if @survey.save
      redirect_to @survey
      flash[:success] = "Survey successfully created!"
    else
      @survey.errors.any?
      flash[:notice] = @survey.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
  end

  def update
    if @survey.update(survey_params)
      redirect_to @survey
      flash[:notice] = "Survey succesfully updated"
    else
      render :edit
    end
  end

  def destroy
    @survey.destroy
    flash[:notice] = "Survey was deleted"
    redirect_to root_path
  end

  private

  def survey_params
    params[:survey].permit(:user_id, :title, questions_attributes: [:id, :prompt, :_destroy, answers_attributes: [:id, :content, :_destroy]])
  end

  def set_survey
    @survey = Survey.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |questions_for_form|
      render(association.to_s.singularize + "_fields", f: questions_for_form)
    end
    link_to(name, '', class: "add_fields", data: { id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <ul>
        <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Take a Survey", surveys_path %></li>
            <li><%= link_to "My Surveys", mysurveys_path %></li>
        <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
    </ul>

    <p class="notice flash-box"><%= notice %></p>
    <p class="alert flash-box"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_form.html.erb
<%= form_for(@survey) do |f| %>

  <% if @survey.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@survey.errors.count, "error") %> prevented this survey from saving</h2>
        <ul>
          <% @survey.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="form-actions">
      <%= f.submit %>
  </div>
<% end %>

<%= link_to "cancel", surveys_path %>

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %>
  <%= f.text_area :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove", '#', class: "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@survey.errors.count, "error") %> prevented this survey from saving</h2>
        <ul>
          <% @survey.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <%= f.fields_for :questions do |questions_for_form| %>
    <%= render 'question_fields', f: questions_for_form %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :questions %>

  <div class="form-actions">
      <%= f.submit %>
  </div>
<% end %>

<%= link_to "Cancel", surveys_path %>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :prompt, "Question" %>
  <%= f.text_area :prompt %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove", '#', class: "remove_fields" %>

  <%= f.fields_for :answers do |answers_for_form| %>
    <%= render 'answer_fields', f: answers_for_form %>
  <% end %>
  <%= link_to_add_fields "Add answer", f, :answers %>
</fieldset>

app/views/surveys/_survey_form.html.erb
<%= form_for @survey do |f| %>
  <% @survey.questions.each do |q| %>
    <%= fields_for q do |question_form| %>
      <%= question_form.text_field :prompt %>

      <% q.answers.each do |a| %>
        <%= fields_for a do |answer_form| %>
          <%= answer_form.text_field :content %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<%= link_to "Back to Surveys", surveys_path %>

app/views/surveys/edit.html.erb
<h1>Edit Survey</h1>

<%= render "form" %>

app/views/surveys/home.html.erb
<h1>This is the landing page</h1>

app/views/surveys/index.html.erb
<h1>This is the index page</h1>
<ul>
    <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
</ul>

<ul>
<% @surveys.each do |survey| %>
    <li><%= link_to survey.title, survey %></li>
    <%= pluralize(survey.questions.size, "Question") %>
<% end %>
</ul>

<%= link_to "New Survey", new_survey_path %>

app/views/surveys/mysurveys.html.erb
<ul>
  <% @surveys.each do |survey| %>
      <li><%= link_to survey.title, survey %></li>
      <%= pluralize(survey.questions.size, "Question") %>
  <% end %>
</ul>

<%= link_to "New Survey", new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey Form</h1>

<%= render "partials/form" %>

app/views/surveys/show.html.erb
<h1>This is the show page for surveys.</h1>

<h3><%= @survey.title %></h3>

<ol class="questions">
  <% @survey.questions.each do |question| %>
    <li>
      <%= question.prompt %>
      <ol class="answers">
        <% question.answers.each do |answer| %>
          <li><%= answer.content %></li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ol>

<%= link_to "Edit", edit_survey_path(@survey) %>